### ISSUE TITLE
"BIGINT value is out of range": Datenpunktpunkt wird nicht migriert - ts.number

### ISSUE THREAD

**Issue by IO-Link** [JackGruber/iobroker_mysql_2_influxdb#5]
Ich habe einige Datenpunkte testweise migriert - hat auch anstandslos geklappt. Bei einem klappt es leider nicht. Es erscheint die Meldung 👍 
`iobroker_mysql_2_influxdb-master# python3 migrate.py "javascript.0.ETA%"
Migrate 'javascript.0.ETA%' datapoint(s) ...

Total metrics in ts_number: 5
javascript.0.ETA_Verbrauch_Daily_JS(ID: 15, type: float) (1/5)
Processing row 1 to 1,000 from LIMIT 0 / 100,000 ts_number - javascript.0.ETA_Verbrauch_Daily_JS (1/5)
Processing row 1,001 to 1,474 from LIMIT 0 / 100,000 ts_number - javascript.0.ETA_Verbrauch_Daily_JS (1/5)

javascript.0.ETA_Aussentemp_Daily_JS(ID: 16, type: float) (2/5)
Traceback (most recent call last):
  File "/home/iobroker_mysql_2_influxdb-master/migrate.py", line 199, in <module>
    migrated += migrate_datapoints("ts_number")
  File "/home/iobroker_mysql_2_influxdb-master/migrate.py", line 167, in migrate_datapoints
    MYSQL_CURSOR.execute(query)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 1163, in read
    self._read_result_packet(first_packet)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 1236, in _read_result_packet
    self._read_rowdata_packet()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 1270, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1690, "BIGINT value is out of range in '`ioBroker`.`m`.`ts` * 1000000'")`

Die anderen Datenpunkte wurde korrekt angelegt. Der betroffene Datentpunkt (ID16) ist auch ein "normaler" Datensatz in ts_number. ICh sehe keinen Unterschied zur ID = 15 (javascript.0.ETA_Verbrauch_Daily_JS, welche geklappt hat.

**Comment by IO-Link** [comment]
Fehler gefunden...
In der table war ein ts-Wert fehlerhaft: 1 Stelle zu viel - wie auch immer das passieren konnte... 
Habe ich manuell behoben - jetzt funktioniert´s!
